# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u $DOCKER_USER -p $DOCKER_PW

build-master:
  stage: build
  script:
    - docker build --pull -t yangdafish/losangelocks:latest .
    - docker push yangdafish/losangelocks:latest
  only:
    - master

build:
  stage: build
  script:
    - docker build --pull -t "yangdafish/losangelocks:$CI_COMMIT_REF_SLUG" .
    - docker push "yangdafish/losangelocks:$CI_COMMIT_REF_SLUG"
  except:
    - master
